# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield
import edc_base.model.fields.uuid_auto_field
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('getresults_sender', '0001_initial'),
        ('getresults_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvDictionary',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(editable=False, help_text='System field. UUID primary key.', primary_key=True, serialize=False)),
                ('field_label', models.CharField(blank=True, editable=False, max_length=25, null=True)),
                ('processing_field', models.CharField(blank=True, choices=[('sender_panel', 'sender_panel'), ('sender', 'sender'), ('serial_number', 'serial_number'), ('collection_date', 'collection_date'), ('order_identifier', 'order_identifier'), ('result_datetime', 'result_datetime'), ('operator', 'operator')], max_length=25, null=True)),
            ],
            options={
                'ordering': ('csv_format__name', 'processing_field'),
            },
        ),
        migrations.CreateModel(
            name='CsvField',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(editable=False, help_text='System field. UUID primary key.', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'ordering': ('csv_format__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CsvFormat',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(editable=False, help_text='System field. UUID primary key.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('header_string', models.TextField(blank=True, null=True)),
                ('sample_file', models.FilePathField(blank=True, help_text='a file to read the header_string from. See also settings.CSV_FILE_PATH and CSV_FILE_EXT', match='\\.csv$', null=True, path='/Users/erikvw/interface/cd4/')),
                ('delimiter', models.CharField(choices=[(',', 'Comma'), ('\t', 'Tab'), (';', 'Semi-colon'), ('|', 'Pipe')], default=',', max_length=5)),
                ('encoding', models.CharField(choices=[('utf_8', 'utf-8'), ('mac_roman', 'mac-roman'), ('latin_1', 'latin-1'), ('utf_16', 'utf-16')], default='utf-8', max_length=25)),
                ('sender_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getresults_sender.SenderModel')),
            ],
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(editable=False, help_text='System field. UUID primary key.', primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=25)),
                ('export_datetime', models.DateTimeField()),
                ('reference', models.CharField(default=uuid.uuid4, max_length=36)),
            ],
            options={
                'ordering': ('-export_datetime',),
            },
        ),
        migrations.CreateModel(
            name='FileImport',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(editable=False, help_text='System field. UUID primary key.', primary_key=True, serialize=False)),
                ('source_filename', models.CharField(max_length=50)),
                ('archive_filename', models.CharField(max_length=50)),
                ('record_count', models.IntegerField(null=True)),
                ('imported', models.BooleanField(default=False)),
                ('import_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'ordering': ('-import_datetime',),
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(editable=False, help_text='System field. UUID primary key.', primary_key=True, serialize=False)),
                ('success', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=50)),
                ('record_count', models.IntegerField(null=True)),
                ('import_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_identifiers', models.TextField(null=True)),
                ('archive', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'ordering': ('-import_datetime',),
            },
        ),
        migrations.AddField(
            model_name='csvfield',
            name='csv_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getresults_csv.CsvFormat'),
        ),
        migrations.AddField(
            model_name='csvdictionary',
            name='csv_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getresults_csv.CsvField'),
        ),
        migrations.AddField(
            model_name='csvdictionary',
            name='csv_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getresults_csv.CsvFormat'),
        ),
        migrations.AddField(
            model_name='csvdictionary',
            name='utestid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getresults_order.Utestid'),
        ),
        migrations.AlterUniqueTogether(
            name='csvfield',
            unique_together=set([('csv_format', 'name')]),
        ),
    ]
